version: '3'
services:
  sync:
    user: app
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    extra_hosts:
      - "rabbitmq:127.0.0.1"
    volumes:
     # Make an ./.env file to define DEV_* vars for your local dev env
     - ${DEV_PROJECT_ROOT:-.}:/app/wpt-sync
     - ${DEV_REPO_ROOT:-./repos}:/app/repos
     - ${DEV_WORKSPACE:-./workspace}:/app/workspace

